clc; close all; clear;
subplot(2,2,1);
plot(0,0,'k-',0,0,'k--');
h(1)=xlabel('Strain');
h(2)=ylabel('Stress');
legend('Unirradiated','Irradiated');
set(gca,'xtick',[],'xticklabel',{},'ytick',[],'yticklabel',{});
axis([0 100 0 0.125]);
set(gca,'Color','none');
subplot(2,2,3);
plot(0,0);
h(1)=xlabel('Strain');
h(2)=ylabel('Stress');
title('FCC');
set(gca,'xtick',[],'xticklabel',{},'ytick',[],'yticklabel',{});
axis([0 100 0 0.125]);
set(gca,'Color','none');
subplot(2,2,4);
plot(0,0);
h(1)=xlabel('Strain');
h(2)=ylabel('Stress');
title('BCC');
set(gca,'xtick',[],'xticklabel',{},'ytick',[],'yticklabel',{});
axis([0 100 0 0.125]);
set(gcf,'Position',[50 50 1000 1000],'PaperPositionMode','auto');
set(gca,'Color','none');
plot2svg('Loss_of_Ductility_Plots.svg');