clc; close all; clear;
subplot(1,2,1);
t=linspace(0,20,1000);
y=gaussmf(t,[2 10]);
plot(t,y,'k-');
xlabel('T');ylabel('\Delta V/V');
set(gca,'xtick',[],'xticklabel',{},'ytick',[],'yticklabel',[]);
axis([0 20 0 1.1]);
set(gca,'Color','none');
subplot(1,2,2);
t=linspace(0,20,1000);
y=t-5;
plot(t,y,'k-');
xlabel('dpa');ylabel('\Delta V/V');
set(gca,'xtick',[5],'xticklabel',{'incubation period'},'ytick',[],'yticklabel',[]);
axis([0 20 0 20]);
set(gcf,'Position',[50 50 1000 450],'PaperPositionMode','auto');
set(gca,'Color','none');
plot2svg('Dose_and_Temperature_Effects_Plot.svg');