#!/bin/bash
###
### The following block runs after commit to "master" branch
###
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then

    # Layout prefix is prepended to each markdown file synced
    ###################################################################
    LAYOUT_PREFIX='---\r\nlayout: post-no-feature\r\n---\r\n\r\n'

    # Switch to gh-pages branch to sync it with master
    ###################################################################
    git checkout gh-pages

    # Sync the README.md in master to index.md adding jekyll header
    ###################################################################
    git checkout master -- README.md
    echo -e $LAYOUT_PREFIX > index.md
    cat README.md >> index.md
    rm README.md
    git add index.md
    git commit -a -m "Sync README.md in master branch to index.md in gh-pages"

    # Sync the markdown files in the docs/* directory
    ###################################################################
    git checkout master -- docs
    FILES=docs/*
    for file in $FILES
    do
        echo -e $LAYOUT_PREFIX | cat - "$file" > temp && mv temp "$file"
    done

    git add docs
    rm temp
    git commit -a -m "Sync docs from master branch to docs gh-pages directory"

    # Sync relational markdown files throughout directory branch
    ####################################################################
    git checkout master
    rel_paths="$(find . -name \*.md -print | tr '\n' ' ' | sed 's:\.\/::g' )"
    git checkout gh-pages
    git checkout master -- $rel_paths
    git checkout master -- hooks/rem.py
    
    for file in $rel_paths
    do
        echo -e $LAYOUT_PREFIX | cat - "$file" > temp && mv temp "$file"
    done

    for file in $rel_paths
    do
        python hooks/rem.py "$file" > temp
        mv temp "$file"
    done

    git add $rel_paths
    rm temp
    find . -name 'README.md' -exec sh -c 'git mv -f "$1" "$( echo $1 | sed 's/README/index/g' )"' _ {} \;
    git commit -am 'updating all of the markdown documentation'

    
    # Uncomment the following push if you want to auto push to
    # the gh-pages branch whenever you commit to master locally.
    # This is a little extreme. Use with care!
    ###################################################################
    # git push origin gh-pages

    # Finally, switch back to the master branch and exit block
    git checkout master
fi

