#!/bin/bash
###
### The following block runs after commit to "master" branch
###
if [ `git rev-parse --abbrev-ref HEAD` == "master" ]; then

    # Switch to gh-pages branch to sync it with master
    ###################################################################
    #git checkout gh-pages

    # Sync the README.md in master to index.md adding jekyll header
    ###################################################################
    #git checkout master -- README.md
    #echo -e $LAYOUT_PREFIX > index.md
    #cat README.md >> index.md
    #rm README.md
    #git add index.md
    #git commit -a -m "Sync README.md in master branch to index.md in gh-pages"

    # Sync the markdown files in the docs/* directory
    ###################################################################
    #git checkout master -- docs
    #FILES=docs/*
    #for file in $FILES
    #do
    #    echo -e $LAYOUT_PREFIX | cat - "$file" > temp && mv temp "$file"
    #done

    #git add docs
    #rm temp
    #git commit -a -m "Sync docs from master branch to docs gh-pages directory"

    # Sync relational markdown files throughout directory branch and put
    # into _pages directory
    ####################################################################
    # get the path of the files ending in *.lyx
    rel_paths="$(find . -name \*.lyx -print | tr '\n' ' ' | sed 's:\.\/::g' )"
    # find the bibliography
    bibs="$(find . -name \*.bib -print | tr '\n' ' ' | sed 's:\.\/::g' )"
    # find the images
    images="$(find . -name \*.tex -print | tr '\n' ' ' | sed 's:\.\/::g' )"
    svgs="$(find . -name \*.svg -print | tr '\n' ' ' | sed 's:\.\/::g' )"
    # then, checkout the pdf branch
    #git checkout pdf
    ## clean the pdf branch
    #git rm -rf *
    ## then, checkout the files ending in *.lyx
    #git checkout master -- "$rel_paths"
    ## checkout the bibs
    #git checkout master -- "$bibs"
    #for file in $bibs
    #do
    #    git add "$file"
    #done
    ##checkout the images
    #git checkout master -- "$images"
    #for file in $images
    #do
    #    git add "$file"
    #done
    ## then, convert the files ending in *.lyx to *.tex
    #for file in $rel_paths
    #do
    #    lyx2.1 --export "latex" "$file"
    #    git add "${file%.lyx}.tex"
    #    rm "$file"
    #    rm "${file%.lyx}.md"
    #done
    ## then, commit the pdf generation files
    #git commit -am 'made the pdf generation files required'
    # then, checkout the gh-pages branch
    git checkout gh-pages
    # clean the paths
    git rm -r Thermal_Hydraulics/
    git rm -r Neutronics/
    git rm -r Interactions/
    git rm -r Materials/
    rm -r Thermal_Hydraulics/
    rm -r Neutronics/
    rm -r Interactions/
    rm -r Materials/
    # then, checkout the files ending in *.lyx
    git checkout master -- $rel_paths
    git checkout master -- hooks/title.lua
    git checkout master -- hooks/date.lua
    # checkout all the bib files
    git checkout master -- $bibs
    for file in $bibs
    do
        git add "$file"
    done
    # checkout all the svgs
    git checkout master -- $svgs
    for file in $svgs
    do
        git add "$file"
    done
    # then, convert the files from *.lyx to *.md
    for file in $rel_paths
    do
        # export to tex
        lyx2.1 --export "latex" "$file"
        # get the document title
        title="$( pandoc -t hooks/title.lua ${file%.lyx}.tex )"
        date="$( pandoc -t hooks/date.lua ${file%.lyx}.tex )"
        # create the new header
        LAYOUT_PREFIX="---\r\nlayout: post-no-feature\r\ndate: $date\r\ntitle: $title\r\n---\r\n\r\n"
        # export to md
        pandoc -o "${file%.lyx}.md" "${file%.lyx}.tex"
        # add yaml header
        mkdir -p "${file%.lyx}"
        echo -e $LAYOUT_PREFIX | cat - "${file%.lyx}.md" > "${file%.lyx}/index.md"
        git add "${file%.lyx}/index.md"
        rm "${file%.lyx}.md"
        rm "${file%.lyx}.tex"
    done
    # remove temp file if its there
    rm temp
    # then, commit the updated markdown files
    git commit -am 'added the updated markdown files'

    # Finally, switch back to the master branch and exit block
    git checkout master
fi
